### ISSUE TITLE
Suggestion: add LICENSE file

### ISSUE THREAD

**Issue by TylerHobanDotCom** [Oreo113/Expression-2#2]
Self explanatory, add a license.

**Comment by Oreo113** [comment]
I am new to GitHub, do you mind exposing what that means? I never heard of a license for GitHub...

**Comment by TylerHobanDotCom** [comment]
Fixed in https://github.com/Oreo113/Expression-2/commit/493ddfc0dda8b32155236a5f46106b135cebf739
